#!/bin/bash

BRANCH='git branch'

if [ $NUM_FAILS -ne 0 ] 
then
	echo -e "${RED}Can't commit! You've broken $NUM_FAILS tests!!!${ENDCOLOR}"
	exit 1
else
	echo -e "${GREEN}All tests passed. You didn't broke anything. Congrats!\n${ENDCOLOR}"
	exit 0
fi
